### ISSUE TITLE
add example/instruction

### ISSUE THREAD

**Issue by santolucito** [dktr0/MusicW#6]
This looks really cool, and I'd like to use it in my class, but I'm not sure how to get started. Are there examples or build instructions?

**Comment by dktr0** [comment]
It's very un(der)-documented that's for sure. The main places it is used are in Estuary https://github.com/dktr0/Estuary and Punctual https://github.com/dktr0/Punctual - the latter is probably more useful in terms of an example of how to setup a build system (because the Estuary one has a bunch of additional complications). Punctual has a nix-based build process with the reflex platform and GHCJS - the key file is called default.nix (and then the Makefile shows how some particular operations in the build process are initiated, and how some build products are moved around). A warning that building the reflex-platform with Nix is a heavy process and it doesn't always work out for everyone on specific computers - that could be a real pain in class settings. In theory it's possible to use GHCJS and reflex-platform via stack, but I haven't tested that in many years at this point. Hope that helps!
